config/routes.rb
Rails.application.routes.draw do
  root "chatroom#index"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  post "message", to: "messages#create"


  resources :users, except: [:new, :create]
  resources :messages
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
    validates :body, presence: true
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    validates :username,  presence: true, length: {minimum: 3, maximum: 15}, uniqueness: {case_sensitive: false}

    has_many :messages

    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?, :require_user
    
    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!current_user
    end

    def require_user
        if !logged_in?
            flash[:alert] = "you must be logged in to perform this action"
            redirect_to login_path
        end
    end
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
    before_action :require_user

    def index
        @messages = Message.all
        @message = Message.new
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    def create
        puts "H# #{message_params}"
        @message = Message.new(message_params)
        @message.user = current_user
        if @message.save
            redirect_back(fallback_location: root_path)
        else
            flash[:error] = "Could not send message"
        end
    end


    private
    def message_params
        params.require(:message).permit(:body)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    before_action :require_logout, only: [:new , :create]

    def new 
    end

    def create
        user = User.find_by(username: params[:session][:username])
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:success] = "Successfully Logged in"
            redirect_to root_path
        else
            flash.now[:error] = "There was something wrong with your information"
            render :new, status: :unprocessable_entity
        end
    end

    def destroy 
        session[:user_id] = nil
        flash[:success] = "Successfully logged out"
        redirect_to login_path
    end

    private
    def require_logout
        if logged_in?
            flash[:alert] = "You are already logged in!, you must log out first."
            redirect_to root_path
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chatroom/_message.html.erb
<p><strong class="text-success"><%= message.user.username%> </strong> added <%= message.body%></p>

app/views/chatroom/index.html.erb
<div class="d-flex justify-content-center mt-5">
    <div class="home-page-icon-container justify-content-center align-items-center d-flex">
         <div class="home-page-icon-inner-container justify-content-center align-items-center d-flex">
            <%= image_tag "favicon.ico", class: "w-75 h-75" %>
        </div>
    </div>
</div>
<h1 class="text-center">Say something</h1>
        <div class="row m-3">
            <div class="col-10">
                <div class="message-box border border-secondary rounded ">
                   <div class="p-3">
                    <% @messages.each do |m|%>
                    <%= render "message" , message: m%>
                    <% end %>
                   </div>

                    <div class="main-message-form">
                        <%= form_with model: @message, url: message_path do |form| %>
                            <div class=" m-3">
                                <div class="input-group mb-3">
                                <%= form.text_field :body,class: "form-control ", placeholder: "Enter Message"  %>
                                <%= form.button  class: 'btn btn-outline-secondary bg-warning' do %>
                                    <i class="fa fa-paper-plane" aria-hidden="true"></i>
                                <% end %>
                                </div>
                            </div>
                        <% end %>
                    </div>
                                        
                </div>
            </div>
            <div class="col-2">
                <div class="message-box border border-secondary rounded p-2">
                    <ul class="list-group">
                        <li class="list-group-item bg-dark text-white">Online Users</li>
                        <li class="list-group-item bg-dark text-white">An item</li>
                        <li class="list-group-item bg-dark text-white">An item</li>
                        <li class="list-group-item bg-dark text-white">An item</li>
                    </ul>
                </div>
            </div>
        </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageMe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <%= favicon_link_tag %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
   
    <%= render "shared/navbar"%>

     <% flash.each do |name, msg|%>
        <div class="alert <%= name == "success"? "alert-success" : "alert-danger"%> alert-dismissible fade show m-2" role="alert">
          <%= msg%>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      <% end %>

    <%= yield %>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarScroll">
      <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
        <li class="nav-item">
          <%= link_to "Home", root_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Messages</a>
        </li>
      </ul>
      <div class="nav-item dropdown me-2 text-muted">
        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          Account
        </a>
        <ul class="dropdown-menu">
          <% if !logged_in? %>
          <li><%= link_to "Login", login_path, class:"dropdown-item" %></li>
          <li><a class="dropdown-item" href="#">Sign Up</a></li>
          <%else%>
          <li><hr class="dropdown-divider"></li>
          <li> 
            <%= button_to "Logout" ,logout_path, class:"dropdown-item",method: :delete, data: {turbo_method: :delete, turbo_message: "Are you sure?"}  %> 
          </li>
          <%end%>
        </ul>
      </div>
      <button class="btn btn-info " type="submit">SignUp</button>
    </div>
  </div>
</nav>